### ISSUE TITLE
A week of social maintenance (recurring)

### ISSUE THREAD

**Issue by zschavi** [leapdao/meta#176]
# Bounty

## Scope
- research & review possible twitter content (through Slack: #07_social_content & own research)
- monitoring the social calendar, proposing & driving content creation, dialogues online
- weekly report on twitter, google analytics, newsletter in general tactical call (written in Slack: #05_communications)

## Deliverables
- regular twitter post (Threads, Single posts or reposts)
- weekly analytics for the socials (twitter, google analytics, newsletter)
- propose ideas & feedback based on website performance

## Gain for the project
- preserve the quality of twitter channel through valuable content & insights to LeapDAO.
- drive engagement to encourage validators & contributors to join LeapDAO.
- track performance of webpage & click-throughs through google analytics

## Roles
bounty gardener/worker: @zschavi / 85%
bounty reviewer: @DistributedDoge  / 15% (@MaxKuck withdrawn)

**Comment by DistributedDoge** [comment]
Approving review for period  13.01.20-20.01.20. 

- Looking at twitter, I can see 6 twitter posts and some more replies/retweets, which seems like acceptable level of activity. I feel like we could have more posts, but this requires content so it is more of a *teamwork* thing, see next point. 

- @zschavi was the only one posting to 07 Social content and posted there once this week. Since it is part of the bounty, it would be good to have a bit more activity here, as it serves as tangible record that ideas are indeed being proposed and helps to justify "S" time. 

- Twitter/newsletter report was published. From what I see we aren't really getting much traction as of now. Maybe we could try engaging in conversation, besides posting stuff on our profile?

- Regarding report analytics itself, it is great it is being done and but I feel like we could brainstorm a more elegant way of presenting statistics than pasting them inside a picture, that would be eaten by slack sooner or later. 

My general feeling is that ongoing work on socials is worthwhile and done to good standard, but review and reporting procedure re:this bounty could be improved.
