### ISSUE TITLE
Newsletter 0x04 - "Phoenix from the Ashes"

### ISSUE THREAD

**Issue by zschavi** [leapdao/meta#216]
# Bounty
new purpose, new strategies, new technologies, new fantasies...
many things happened the last weeks, let's inform the world!

## Scope
- draft a insightful & sharp text for the email.
- setup newsletter mail template.
- setup campaign & timing to send email.

## Deliverables
Send a newsletter to followers, informing about:
- adjusting the purpose, new strategies of LeapDAO
- mainnet shutdown & testnet updates (6.0.0 etc.)
- Colony + Holacracy Blog
- gitcoin round 5
- EMO

## Gain for the project
- proof of activity to followers and contributors
- transparent flow of information about our DAO

## Roles
bounty gardener & worker: @zschavi / 85%
bounty reviewer: @saumyabratadutt / 15%

**Comment by saumyabratadutt** [comment]
🤚
I'm up for review.

**Comment by zschavi** [comment]
# Leap Newsletter 0x04 - basic structure

## Intro

## Ecosystem Updates
* link the post of Mainnet shutdown
&
* mention new purpose + new strategies
* briefly explain new technologies and what they offer

* link Tribe DAO post + introduce the idea

* announce leapDAO's attendance at events

## Geek Garden
* new releases for testnet
* zK calls (?)

## Outro
* join slack
* bounties & roles for grab

### footer

**Comment by saumyabratadutt** [comment]
This is good, should we include recent exploits mainly because DeFi is emerging?

**Comment by zschavi** [comment]
Normally we only publish LeapDAO related information...or Plasma/Layer2 topics.

If you can propose some insights to this recent exploit/hack + how could plasma help to avoid such things, we would have a fitting paragraph 👍 

I will update the above draft with content once it's ready.
Hope we can ship the newsletter by end of week, or starting next one 💯

**Comment by saumyabratadutt** [comment]
Sure. I will post some insights soon.

**Comment by saumyabratadutt** [comment]
bZX 15 Feb attack was due to logical error. This could have been avoided by testing the code sufficiently. Finding logical errors are tough, especially when the programs doesn't flag problems in initial testing environment.
More on the attack [https://www.palkeo.com/en/projets/ethereum/bzx.html#b-the-compound-borrow](url)

Second attack is of special interest since it exploited Oracle. The attack was well-thought. The basic of the attack was to eat up the liquidity from price feed provider hence screwing the price and using the screwed price to profit. Using single price feed especially from DEX with low liquidity can be dangerous, because it can be manipulated. These maybe fixed by using price feed of several external off-chain liquidity providers and exchanges because they have high liquidity plus using several of those can make manipulation harder.

**Comment by zschavi** [comment]
Will catch up on the Newsletter tomorrow, results are posted as soon as they are ready

**Comment by zschavi** [comment]
as mentioned on 10 March, new structure.

this bounty is closed, due to long inactivitiy
